[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"

[project]
name = "whichprovides"
requires-python = ">=3.9"
license = "MIT"
license-files = ["LICENSE"]
dynamic = ["version"]

[tool.hatch.version]
path = "src/whichprovides/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
  "src/whichprovides/",
  "tests/"
]

[tool.hatch.build.targets.wheel]
packages = ["src/whichprovides"]
