[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"

[project]
name = "whichprovides"
description = "Module which provides 'yum provides' functionality across many package managers"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
license-files = ["LICENSE"]
dynamic = ["version"]

[project.urls]
"Home Page" = "https://github.com/sethmlarson/whichprovides"
"Documentation" = "https://github.com/sethmlarson/whichprovides"
"Source Code" = "https://github.com/sethmlarson/whichprovides"

[tool.hatch.version]
path = "src/whichprovides/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
  "src/whichprovides/",
  "tests/"
]

[tool.hatch.build.targets.wheel]
packages = ["src/whichprovides"]

[tool.mypy]
mypy_path = "src"
exclude = [
  "^tests/.*"
]
